### ISSUE TITLE
Dependency Injection with  Dagger 2 Setup

### ISSUE THREAD

**Issue by JohnItoo** [CottaCush/AndroidBaseProject#14]
Setup Dependency Injection for The Android Base Project. This is to allow Devs use DI in newer projects.

**Comment by JubrilEdu** [comment]
Anything on this? @JohnItoo @oyeleke

**Comment by JohnItoo** [comment]
We have done this. We added the dependencies and the necessary files. I think the issue can be closed.

**Comment by JohnItoo** [comment]
This is the PR. https://github.com/CottaCush/AndroidBaseProject/pull/15 where it was done
